name: "Notify Discord"
description: "Sends a notification to a Discord channel"
inputs:
  branch:
    description: "The branch that was pushed to"
    required: true
    default: "master"
  token:
    description: "The Discord bot token"
    required: true
  repo_tree:
    description: "The repository tree"
    required: true
runs:
  using: "node16"
  main: "src/index.js"
